name: Beard CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:

    ##############################
    #
    # INSTALL AND RUN THE UI TESTS
    #
    - uses: actions/checkout@v2

    - name: Install Node.js 12.13.0
      uses: actions/setup-node@v1
      with:
        node-version: 12.13.0

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
